name: Generate Snake

on:
  schedule:
    # Her 6 saatte bir çalışır
    - cron: "0 */6 * * *"
  workflow_dispatch: # Manuel olarak çalıştırmanı sağlar

jobs:
  build:
    runs-on: ubuntu-latest
    # İşlemin depoya yazabilmesi için gerekli izinleri ekliyoruz
    permissions:
      contents: write
    
    steps:
      # Depoyu kontrol eder (v4 güncel sürümdür)
      - uses: actions/checkout@v4

      # Yılan animasyonunu oluşturur (v3 güncel ve kararlı sürümdür)
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: nyxstorm
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.gif

      # Oluşturulan dosyaları 'output' branch'ine yükler
      - name: Push changes
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
